# Generated by Django 5.1.3 on 2024-12-01 22:59

import dj_2to3.models.python
import django.db.models.deletion
import django_extensions.db.fields
import versionfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dj_2to3", "0000_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Future",
            fields=[
                (
                    "created",
                    django_extensions.db.fields.CreationDateTimeField(
                        auto_now_add=True, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    django_extensions.db.fields.ModificationDateTimeField(
                        auto_now=True, verbose_name="modified"
                    ),
                ),
                (
                    "version",
                    versionfield.fields.VersionField(primary_key=True, serialize=False),
                ),
            ],
            options={
                "get_latest_by": "modified",
                "abstract": False,
            },
        ),
    ]
